import { CHAIN_ID } from 'src/app/constants/networks';

export const DEPLOYMENT_BLOCK = {
  [CHAIN_ID.MAINNET]: 13135260,
  [CHAIN_ID.POLYGON]: 19856040,
  [CHAIN_ID.FANTOM]: 18889117,
  [CHAIN_ID.AVALANCHE]: 5354349,
};

export const DEPLOYMENT_TIMESTAMP = {
  [CHAIN_ID.MAINNET]: 1630438797,
  [CHAIN_ID.POLYGON]: 1633405322,
  [CHAIN_ID.FANTOM]: 1634014867,
  [CHAIN_ID.AVALANCHE]: 1633658834,
};

export const MPH_DEPLOYMENT_TIMESTAMP = {
  [CHAIN_ID.MAINNET]: 1605809018,
  [CHAIN_ID.POLYGON]: null,
  [CHAIN_ID.FANTOM]: null,
  [CHAIN_ID.AVALANCHE]: null,
};

export const BALANCER_DEPLOYMENT_TIMESTAMP = {
  [CHAIN_ID.MAINNET]: 1657812209,
  [CHAIN_ID.POLYGON]: null,
  [CHAIN_ID.FANTOM]: null,
  [CHAIN_ID.AVALANCHE]: null,
};

export const BANCOR_V2_DEPLOYMENT_TIMESTAMP = {
  [CHAIN_ID.MAINNET]: 1617580800,
  [CHAIN_ID.POLYGON]: null,
  [CHAIN_ID.FANTOM]: null,
  [CHAIN_ID.AVALANCHE]: null,
};

export const BANCOR_V3_DEPLOYMENT_TIMESTAMP = {
  [CHAIN_ID.MAINNET]: 1654808870,
  [CHAIN_ID.POLYGON]: null,
  [CHAIN_ID.FANTOM]: null,
  [CHAIN_ID.AVALANCHE]: null,
};

export const UNISWAP_V2_DEPLOYMENT_TIMESTAMP = {
  [CHAIN_ID.MAINNET]: 1605812592,
  [CHAIN_ID.POLYGON]: null,
  [CHAIN_ID.FANTOM]: null,
  [CHAIN_ID.AVALANCHE]: null,
};

export const UNISWAP_V3_DEPLOYMENT_TIMESTAMP = {
  [CHAIN_ID.MAINNET]: 1620348065,
  [CHAIN_ID.POLYGON]: null,
  [CHAIN_ID.FANTOM]: null,
  [CHAIN_ID.AVALANCHE]: null,
};

export const SUSHISWAP_DEPLOYMENT_TIMESTAMP = {
  [CHAIN_ID.MAINNET]: 1608163810,
  [CHAIN_ID.POLYGON]: null,
  [CHAIN_ID.FANTOM]: null,
  [CHAIN_ID.AVALANCHE]: null,
};
